### ISSUE TITLE
Question: Is there a seed preprocessing in cycle-crypt?

### ISSUE THREAD

**Issue by alpominth** [duzun/cycle-crypt#12]
Taking a look at speed measurements of [SHAKE-256](https://codeberg.org/maandree/sha3sum) (that can work as a stream cipher) I get the following timings:

Hashing a 1GB input:
```
$ time dd if=/dev/zero count=32768 bs=32768 | shake256sum -N 8
32768+0 records in
32768+0 records out
1073741824 bytes (1.1 GB, 1.0 GiB) copied, 4.85688 s, 221 MB/s
b4  -
real	0m4.859s
user	0m4.628s
sys	0m0.729s
```

Producing a 1GiB output:
```
time dd if=/dev/zero count=1 bs=1 | shake256sum -N 8589934592 > /dev/null 
1+0 records in
1+0 records out
1 byte copied, 2.9014e-05 s, 34.5 kB/s
real	0m6.540s
user	0m5.722s
sys	0m0.819s
```

Hashing a 1GiB input and producing a 1GiB output:
```
$ time dd if=/dev/zero count=32768 bs=32768 | shake256sum -N 8589934592 > /dev/null 
32768+0 records in
32768+0 records out
1073741824 bytes (1.1 GB, 1.0 GiB) copied, 4.65244 s, 231 MB/s
real	0m11.114s
user	0m9.980s
sys	0m1.614s
```

I can conclude that nearly half the CPU cycles per core was used to setup the internal state of SHAKE-256 and another half to generate the output.

Does the modified xorshift+ used by cycle-crypt needs to perform a "setup" with the seed in the internal state before emit the output like SHAKE-256 does? If yes, does the "setup" performed consumes nearly half the CPU cycles needed to transform a seed into a random output?

Resuming the question: Is the xorshift+ variant used by cycle-crypt [Salsa20](https://en.wikipedia.org/wiki/Salsa20)-like that processes the input (key+nonce+counter) directly?

**Comment by duzun** [comment]
It's difficult to compare `SHAKE-256` with `cycle-crypt`, because the concepts are different.

To answer your question, `cycle-crypt` has a state initialization stage at the beginning, which is based on the seed and the key. There is no seed processing afterwards.
The size of the state equals the size of the key, which could have an impact on processing speed, because the state is mutated after it is "consumed" during encryption. The smaller the state, the more mutations are required.

Encrypting a 1Gb input using a 32Kb key (and state), thus  1Gb / 32Kb = 32 768 state updates:

```sh
> key32k="0x$(dd if=/dev/random count=32768 bs=1 2>/dev/null | xxd -p -c 32768)";
> time dd if=/dev/zero count=32768 bs=32768 | ./bin/cycry.js -k "$key32k" -so /tmp/salt32k | wc -c
32768+0 records in
32768+0 records out
1073741824 bytes (1,1 GB, 1,0 GiB) copied, 3,45846 s, 310 MB/s
1073741824

real	0m3,472s
user	0m2,674s
sys	0m1,019s

> cat /tmp/salt32k | wc -c # auto-generated salt
32768
```

Encrypting a 1Gb input using a 4b key (and state), thus 1Gb / 4b = 268 435 456 state updates:

```sh
> key4b="0x$(dd if=/dev/random count=4 bs=1 2>/dev/null | xxd -p -c 4)";
> time dd if=/dev/zero count=32768 bs=32768 | ./bin/cycry.js -k "$key4b" -so /tmp/salt4b | wc -c
32768+0 records in
32768+0 records out
1073741824 bytes (1,1 GB, 1,0 GiB) copied, 4,21396 s, 255 MB/s
1073741824

real	0m4,229s
user	0m3,183s
sys	0m1,182s

> cat /tmp/salt4b | wc -c # auto-generated salt
4
```

If trying to compute number of state updates per second (even though this is not exact calculation, using user time):
(268 435 456 - 32 768) / (3.183s - 2.674s) = 527 313 728 Hz

I'm running these command on a VM. For comparison, here is shake256sum for 1Gb input & 1Gb output on the same VM:

```sh
> time dd if=/dev/zero count=32768 bs=32768 | shake256sum -N 8589934592 -b | wc -c
32768+0 records in
32768+0 records out
1073741824 bytes (1,1 GB, 1,0 GiB) copied, 5,48213 s, 196 MB/s
1073741824

real	0m11,695s
user	0m9,800s
sys	0m2,252s
```

**Comment by duzun** [comment]
If by input you mean the key and by the output - the initial state, then yes, the same CPU cycles would be use as when computing the full size initial state.

**Comment by duzun** [comment]
P.S. XorShift+ is not a hash function. Nor cycle-crypt is.

**Comment by duzun** [comment]
> But if the key and the initial state can be any size, a (maybe non-cryptographic) hash function can be built out of the modified Xorshift+ used by cycle-crypt, right?

You have the right intuition here. The [internal function](https://github.com/duzun/cycle-crypt/blob/master/CycleCrypt.js#L116) that generates the state from the key and the seed is a keyed hash function, somewhat resembling the PBKDF2.

**Comment by duzun** [comment]
IMU you need a password-based crypto-secure PRNG.
